apiVersion: v1
kind: Pod
metadata:
  name: pvc-access-pod
spec:
  containers:
    - name: busybox
      image: docker.io/busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /madara/data
          name: madara-data-1
  volumes:
    - name: madara-data-1
      persistentVolumeClaim:
        claimName: madara-pvc
  restartPolicy: Never