apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pathfinder-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: hdd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pathfinder-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: hdd
